import pytest

from agents.investigation_agent import InvestigationAgent
from agents.report_generators.base import ReportGenerator
from agents.report_generators.template_report_generator import TemplateReportGenerator
from agents.report_generators.templates import (
    BRUTE_FORCE_ATTACK,
    DATA_EXFILTRATION,
    PRIVILEGE_ESCALATION,
)
from app.schemas.investigation_report import InvestigationReport
from app.schemas.security_finding import SecurityFinding


def make_finding(
    finding_type: str,
    severity: str = "HIGH",
    description: str = "Test finding description.",
    affected_user: str = "admin",
    source_ip: str = "1.2.3.4",
) -> SecurityFinding:
    return SecurityFinding(
        finding_type=finding_type,
        severity=severity,
        description=description,
        affected_user=affected_user,
        source_ip=source_ip,
    )


def test_investigate_empty_findings_returns_empty_list():
    agent = InvestigationAgent()
    assert agent.investigate([]) == []


def test_brute_force_report_has_expected_fields():
    finding = make_finding(
        finding_type=BRUTE_FORCE_ATTACK,
        description="5 failed login attempts followed by a successful login.",
    )

    report = InvestigationAgent().investigate_one(finding)

    assert isinstance(report, InvestigationReport)
    assert report.incident_title == "Brute Force Attack Targeting admin"
    assert report.severity == "HIGH"
    assert "brute force attack" in report.summary.lower()
    assert finding.description in report.evidence
    assert "Reset the affected user's password immediately." in report.recommendations


def test_privilege_escalation_report_has_expected_fields():
    finding = make_finding(
        finding_type=PRIVILEGE_ESCALATION,
        severity="CRITICAL",
        description="User logged in and was granted elevated privileges.",
        affected_user="alice",
    )

    report = InvestigationAgent().investigate_one(finding)

    assert report.incident_title == "Privilege Escalation by alice"
    assert report.severity == "CRITICAL"
    assert "elevated privileges" in report.summary.lower()
    assert "Affected user: alice" in report.evidence
    assert "Verify whether the privilege grant was authorized and expected." in report.recommendations


def test_data_exfiltration_report_has_expected_fields():
    finding = make_finding(
        finding_type=DATA_EXFILTRATION,
        description="User accessed 3 files, then performed a large download.",
        affected_user="carol",
        source_ip="10.0.0.5",
    )

    report = InvestigationAgent().investigate_one(finding)

    assert report.incident_title == "Possible Data Exfiltration by carol"
    assert "data exfiltration" in report.summary.lower()
    assert "Source IP: 10.0.0.5" in report.evidence
    assert "Identify which files were accessed and downloaded." in report.recommendations


def test_investigate_processes_multiple_findings():
    findings = [
        make_finding(BRUTE_FORCE_ATTACK, affected_user="admin"),
        make_finding(PRIVILEGE_ESCALATION, severity="CRITICAL", affected_user="alice"),
        make_finding(DATA_EXFILTRATION, affected_user="carol"),
    ]

    reports = InvestigationAgent().investigate(findings)

    assert len(reports) == 3
    assert reports[0].incident_title.startswith("Brute Force Attack")
    assert reports[1].incident_title.startswith("Privilege Escalation")
    assert reports[2].incident_title.startswith("Possible Data Exfiltration")


def test_unknown_finding_type_raises_error():
    finding = make_finding(finding_type="Unknown Attack")

    with pytest.raises(ValueError, match="No report template available"):
        TemplateReportGenerator().generate(finding)


def test_investigation_agent_accepts_custom_report_generator():
    class StubReportGenerator(ReportGenerator):
        def generate(self, finding: SecurityFinding) -> InvestigationReport:
            return InvestigationReport(
                incident_title="Stub Report",
                severity=finding.severity,
                summary="Generated by stub generator.",
                evidence=[finding.description],
                recommendations=["Run stub playbook."],
            )

    finding = make_finding(BRUTE_FORCE_ATTACK)
    report = InvestigationAgent(report_generator=StubReportGenerator()).investigate_one(
        finding
    )

    assert report.incident_title == "Stub Report"
    assert report.summary == "Generated by stub generator."


def test_investigation_report_requires_non_empty_evidence_and_recommendations():
    with pytest.raises(Exception):
        InvestigationReport(
            incident_title="Test Incident",
            severity="LOW",
            summary="Test summary.",
            evidence=[],
            recommendations=["One recommendation."],
        )


def test_template_generator_uses_finding_metadata_in_evidence():
    finding = make_finding(
        finding_type=BRUTE_FORCE_ATTACK,
        severity="HIGH",
        affected_user="jsmith",
        source_ip="192.168.1.10",
    )

    report = TemplateReportGenerator().generate(finding)

    assert report.evidence == [
        finding.description,
        "Affected user: jsmith",
        "Source IP: 192.168.1.10",
        "Finding severity: HIGH",
    ]
